SisMed/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('paginas.urls')),
    path('', include('cadastros.urls')),
    path('', include('usuarios.urls')),
    path('', include('relatorios.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cadastros/urls.py
from django.urls import path
from .views import AgendaDetail, AniversariosPacientesList, CargoCreate, CargoList, CargoUpdate, CargoDelete, EspecialidadeCreate, EspecialidadeDelete, EspecialidadeList, EspecialidadeUpdate, FuncionarioCreate, FuncionarioDelete, FuncionarioDetail, FuncionarioList, FuncionarioUpdate, HorarioCreate, HorarioDelete, HorarioUpdate, MedicoCreate, MedicoDelete, MedicoDetail, MedicoList, MedicoUpdate, PacienteCreate, PacienteDelete, PacienteDetail, PacienteList, PacienteUpdate, PacientesMedico, ProcedimentoCreate, ProcedimentoDelete, ProcedimentoList, ProcedimentoUpdate

urlpatterns = [
    path('cadastrar/cargo', CargoCreate.as_view(), name='cadastrar-cargo'),
    path('cadastrar/funcionario', FuncionarioCreate.as_view(), name='cadastrar-funcionario'),
    path('cadastrar/especialidade', EspecialidadeCreate.as_view(), name='cadastrar-especialidade'),
    path('cadastrar/medico', MedicoCreate.as_view(), name='cadastrar-medico'),
    path('cadastrar/paciente', PacienteCreate.as_view(), name='cadastrar-paciente'),
    path('cadastar/procedimento', ProcedimentoCreate.as_view(), name='cadastrar-procedimento'),
    
    path('cadastrar/horario/agenda<int:pk>', HorarioCreate.as_view(), name='cadastrar-horario'),
    path('editar/agenda<int:fk>/horario<int:pk>', HorarioUpdate.as_view(), name='editar-agenda'),
    path('excluir/horario<int:pk>/agenda<int:fk>', HorarioDelete.as_view(), name='excluir-horario'),

    path('editar/cargo/<int:pk>', CargoUpdate.as_view(), name='editar-cargo'),
    path('editar/funcionario/<int:pk>', FuncionarioUpdate.as_view(), name='editar-funcionario'),
    path('editar/especialidade/<int:pk>', EspecialidadeUpdate.as_view(), name='editar-especialidade'),
    path('editar/medico/<int:pk>', MedicoUpdate.as_view(), name='editar-medico'),
    path('editar/paciente/<int:pk>', PacienteUpdate.as_view(), name='editar-paciente'),
    path('editar/procedimento/<int:pk>', ProcedimentoUpdate.as_view(), name='editar-procedimento'),

    path('excluir/cargo/<int:pk>', CargoDelete.as_view(), name='excluir-cargo'),
    path('excluir/funcionario/<int:pk>', FuncionarioDelete.as_view(), name='excluir-funcionario'),
    path('excluir/especialidade/<int:pk>', EspecialidadeDelete.as_view(), name='excluir-especialidade'),
    path('excluir/medico/<int:pk>', MedicoDelete.as_view(), name='excluir-medico'),
    path('excluir/paciente/<int:pk>', PacienteDelete.as_view(), name='excluir-paciente'),
    path('excluir/procedimento/<int:pk>', ProcedimentoDelete.as_view(), name='excluir-procedimento'),
    #path('excluir/endereco/<int:pk>', EnderecoDelete.as_view(), name='excluir-endereco'),

    path('listar/cargos', CargoList.as_view(), name='listar-cargos'),
    path('listar/funcionarios', FuncionarioList.as_view(), name='listar-funcionarios'),
    path('listar/especialidades', EspecialidadeList.as_view(), name='listar-especialidades'),
    path('listar/medicos', MedicoList.as_view(), name='listar-medicos'),
    path('listar/pacientes', PacienteList.as_view(), name='listar-pacientes'),
    path('listar/pacientes/medico', PacientesMedico.as_view(), name='listar-pacientes-medico'),
    path('aniversarios/pacientes', AniversariosPacientesList.as_view(), name='aniversarios-pacientes'),
    path('aniversarios/mes', AniversariosPacientesList.as_view(), name='aniversarios-mes'),
    path('listar/procedimentos', ProcedimentoList.as_view(), name='listar-procedimentos'),

    path('dados/funcionario/<int:pk>', FuncionarioDetail.as_view(), name='dados-funcionario'),
    path('dados/medico/<int:pk>', MedicoDetail.as_view(), name='dados-medico'),
    path('dados/paciente/<int:pk>', PacienteDetail.as_view(), name='dados-paciente'),
    path('dados/agenda/<int:pk>', AgendaDetail.as_view(), name='dados-agenda'),
]

cadastros/models.py
from django.db import models
from datetime import date, datetime
from django.contrib.auth.models import User

sexo_opcoes = (('M', 'Masculino'), ('F', 'Feminino'))
boolean_opcoes = ((True, 'Sim'), (False, 'Não'))
tipo_agendamento_opcoes = (('Consulta', 'Consulta'), ('Procedimento', 'Procedimento'))
tipo_pagamento_opcoes = (('Plano', 'Plano'), ('Particular', 'Particular'))
dias_semana_opcoes = ((0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'))

# Create your models here.
class Endereco(models.Model):
    rua = models.CharField(max_length=50)
    numero = models.IntegerField(null=True, blank=True, verbose_name='Número')
    bairro = models.CharField(max_length=50)
    cidade = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.rua} {self.numero} {self.bairro} {self.cidade}'


class Cargo(models.Model):
    nome_cargo = models.CharField(max_length=50, unique=True, verbose_name='Nome do cargo')
    salario = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Salário')

    def __str__(self):
        return f'{self.nome_cargo} {self.salario}'


class Funcionario(models.Model):
    nome_completo = models.CharField(max_length=100, verbose_name='Nome Completo')
    data_nascimento = models.DateField(verbose_name='Data de Nascimento')
    rg = models.CharField(max_length=13, verbose_name='RG', unique=True)
    cpf = models.CharField(max_length=14, verbose_name='CPF', unique=True)
    sexo = models.CharField(max_length=1, choices=sexo_opcoes, null=True) 
    endereco = models.OneToOneField(Endereco, null=True, on_delete=models.PROTECT)
    telefone = models.CharField(max_length=15, unique=True) 
    email = models.CharField(max_length=50, unique=True) 
    data_admissao = models.DateField(null=True, verbose_name='Data de Admissão')
    data_demissao = models.DateField(null=True, blank=True, verbose_name='Data de Demissão')
    cargo = models.ForeignKey(Cargo, on_delete=models.PROTECT) 
    foto =  models.ImageField(upload_to='fotos_funcionarios', blank=True, null=True)
    usuario = models.OneToOneField(User, null=True, blank=True, on_delete=models.DO_NOTHING)

    def get_idade(self):
        hoje = datetime.now().date()
        idade = hoje.year - self.data_nascimento.year - ((hoje.month, hoje.day) < (self.data_nascimento.month, self.data_nascimento.day))
        return idade

    def __str__(self):
        return f'{self.nome_completo}'

    """def __str__(self):
        return f'{self.nome_completo} {self.data_nascimento} {self.rg} {self.cpf} {self.endereco} {self.telefone} {self.email} {self.data_admissao} {self.data_demissao} {self.cargo}'"""


class Especialidade(models.Model):
    especialidade = models.CharField(max_length=30, unique=True)
    valor_consulta = models.DecimalField(max_digits=8, decimal_places=2, null=True)

    def __str__(self):
        return f'{self.especialidade}'


class Medico(models.Model):
    nome_completo = models.CharField(max_length=100, verbose_name='Nome Completo')
    data_nascimento = models.DateField(verbose_name='Data de Nascimento')
    rg = models.CharField(max_length=13, verbose_name='RG', unique=True)
    cpf = models.CharField(max_length=14, verbose_name='CPF', unique=True)
    crm = models.CharField(null=True, max_length=14, verbose_name='CRM', unique=True)
    sexo = models.CharField(max_length=1, choices=sexo_opcoes, null=True) 
    endereco = models.OneToOneField(Endereco, null=True, on_delete=models.PROTECT)
    telefone = models.CharField(max_length=15, unique=True) 
    email = models.CharField(max_length=50, unique=True) 
    data_cadastro = models.DateField(verbose_name='Data de Cadastro') 
    especialidade = models.ForeignKey(Especialidade, on_delete=models.PROTECT)
    foto =  models.ImageField(upload_to='fotos_medicos', blank=True, null=True)
    usuario = models.OneToOneField(User, null=True, on_delete=models.DO_NOTHING)

    def save(self, *args, **kwargs):
        if not self.data_cadastro:
            self.data_cadastro = date.today()
        super().save(*args, **kwargs)

    def get_idade(self):
        hoje = datetime.now().date()
        idade = hoje.year - self.data_nascimento.year - ((hoje.month, hoje.day) < (self.data_nascimento.month, self.data_nascimento.day))
        return idade
    
    def __str__(self):
        return f'{self.nome_completo} - {self.especialidade}'

    """def __str__(self):
        return f'{self.nome_completo} {self.data_nascimento} {self.rg} {self.cpf} {self.crm} {self.endereco} {self.telefone} {self.email} {self.data_cadastro} {self.especialidade}'"""


class Paciente(models.Model):
    nome_completo = models.CharField(max_length=100, verbose_name='Nome Completo')
    data_nascimento = models.DateField(verbose_name='Data de Nascimento')
    rg = models.CharField(max_length=13, verbose_name='RG', unique=True)
    cpf = models.CharField(max_length=14, verbose_name='CPF', unique=True)
    sexo = models.CharField(max_length=1, choices=sexo_opcoes, null=True) 
    endereco = models.OneToOneField(Endereco, null=True, on_delete=models.PROTECT)
    telefone = models.CharField(max_length=15) 
    email = models.CharField(max_length=50) 
    data_cadastro = models.DateField(verbose_name='Data de Cadastro') 
    informacoes_medicas = models.TextField(verbose_name='Informações Médicas')
    foto =  models.ImageField(upload_to='fotos_pacientes', blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.data_cadastro:
            self.data_cadastro = date.today()
        super().save(*args, **kwargs)

    def get_idade(self):
        hoje = datetime.now().date()
        idade = hoje.year - self.data_nascimento.year - ((hoje.month, hoje.day) < (self.data_nascimento.month, self.data_nascimento.day))
        return idade

    def __str__(self):
        return f'{self.nome_completo}'

    """def __str__(self):
        return f'{self.nome_completo} {self.data_nascimento} {self.rg} {self.cpf} {self.endereco} {self.telefone} {self.email} {self.data_cadastro} {self.informacoes_medicas}'"""
    

class HorarioAtendimento(models.Model):
    horario_atendimento = models.TimeField(unique=True)

    def __str__(self):
        return f'{self.horario_atendimento}'


class AgendaMedico(models.Model):
    medico = models.OneToOneField(Medico, on_delete=models.CASCADE)
    
    def __str__(self):
        return f'{self.medico}'


class HorarioMedico(models.Model):
    agenda = models.ForeignKey(AgendaMedico, null=True, on_delete=models.CASCADE)
    dia_semana = models.IntegerField(choices=dias_semana_opcoes)
    horario_inicial_manha = models.TimeField(null=True, blank=True)
    horario_final_manha = models.TimeField(null=True, blank=True)
    horario_inicial_tarde = models.TimeField(null=True, blank=True)
    horario_final_tarde = models.TimeField(null=True, blank=True)


class Prontuario(models.Model):
    data_criacao = models.DateField()
    paciente = models.OneToOneField(Paciente, on_delete=models.PROTECT)

    def save(self, *args, **kwargs):
        if not self.data_criacao:
            self.data_criacao = date.today()
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.data_criacao} {self.paciente}'


class Procedimento(models.Model): 
    nome_procedimento = models.CharField(max_length=50, null=True)
    especialidade_responsavel = models.ForeignKey(Especialidade, on_delete=models.PROTECT, null=True, blank=True)
    descricao = models.TextField(null=True, verbose_name='Descricão')
    valor_procedimento = models.DecimalField(max_digits=8, decimal_places=2, null=True)
    observacao = models.TextField(null=True, blank=True, verbose_name='Observações Gerais Sobre o Procedimento')

    def __str__(self):
        return f'{self.nome_procedimento}' 
    

class Agendamento(models.Model):
    tipo_agendamento = models.CharField(max_length=12, default='Consulta', choices=tipo_agendamento_opcoes, verbose_name='Tipo de agendamento')
    procedimento = models.CharField(max_length=50, null=True, blank=True)
    data = models.DateField(null=True)
    horario = models.TimeField(null=True, verbose_name='Horário')
    paciente = models.ForeignKey(Paciente, on_delete=models.PROTECT)
    medico = models.ForeignKey(Medico, on_delete=models.PROTECT)
    tipo_pagamento = models.CharField(max_length=10, default='Particular', choices=tipo_pagamento_opcoes, verbose_name='Tipo de pagamento')
    retorno = models.BooleanField(default=False, choices=boolean_opcoes)
    valor = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Valor')
    concluido = models.BooleanField(default=False, null=True)

    def __str__(self):
        return f'{self.tipo} {self.data} {self.horario} {self.paciente} {self.medico} {self.concluido}' 


class Atendimento(models.Model):
    data = models.DateField(null=True)
    consulta = models.OneToOneField(Agendamento, on_delete=models.PROTECT)
    anamnese_paciente = models.TextField(verbose_name="Anamnese do paciente")
    diagnostico = models.TextField(verbose_name="Diagnóstico")
    receituario = models.TextField(verbose_name="Receituário/Recomendações") 

    def save(self, *args, **kwargs):
        if not self.data:
            self.data = date.today()
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.nota_medico} {self.paciente} {self.medico}'

cadastros/templates/cadastros/form.html
{% extends 'paginas/index.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
{% endblock %}

{% block content %}

    <div class="form-container">
        <div class="form-box"> 

            <h5 class="titulo-form">{{titulo}}</h5> <br>

            <form method="POST">

                {% csrf_token %}
        
                {% if 'Especialidade' in titulo %}
                    <div class="input-field">
                        {{ form.especialidade }}
                        <label for="{{ form.especialidade.id_for_label }}">Especialidade</label>
                    </div>
                    <div class="input-field">
                        {{ form.valor_consulta }}
                        <label for="{{ form.especialidade.id_for_label }}">Valor da Consulta</label>
                    </div>
                {% elif 'Cargo' in titulo %}
                    <div class="input-field">
                        {{ form.nome_cargo }}
                        <label for="{{ form.nome_cargo.id_for_label }}">Cargo</label>
                    </div>
                    <div class="input-field">
                        {{ form.salario }}
                        <label for="{{ form.salario.id_for_label }}">Salário</label>
                    </div>
                {% elif 'Procedimento' in titulo %}
                    <div class="input-field">
                        {{ form.nome_procedimento }}
                        <label for="{{ form.nome_procedimento.id_for_label }}">Procedimento</label>
                    </div>
                    <div class="input-field">
                        {{ form.especialidade_responsavel }}
                    </div>
                    <div class="text-field" id="text-descricao">
                        <label for="{{ form.descricao.id_for_label }}">Descrição</label>
                        {{ form.descricao }}
                    </div>
                    <div class="input-field">
                        {{ form.valor_procedimento }}
                        <label for="{{ form.valor_procedimento.id_for_label }}">Valor</label>
                    </div>
                {% endif %}

                <div class="card-action">
                    <button type="submit" class="btn btn-form">Salvar</button>
                </div>
        
            </form>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    <script>
        M.AutoInit();
    </script>

<script>
    $(document).ready(function() {
        
    });
</script>
{% endblock %}

cadastros/templates/cadastros/form_excluir.html
{% extends 'paginas/index.html' %}

{% load static %}

{% block styles %}
    <style>

        h4 {
            margin-bottom: 5px;
        }

        p {
            font-size: 17px;
        }

        #registro {
            color: #df8080;
            font-weight: 500;
        }

        .btn {
            background-color: #e48d8d;
        }
        
        .btn:hover {
            background-color: #df8686;
        }

    </style>
{% endblock %}

{% block content %}
    
    <div class="form-container">
        <h4>Excluir Registro</h4> <br>
    
        <p>Deseja excluir {{objeto}} <span id="registro">{{registro}}</span> definitivamente?</p> <hr> <br>

        <form method="POST">

            {% csrf_token %}
    
            {{ form.as_p }}
    
            <button type="submit" class="btn">Excluir</button>
    
        </form>
    </div>

{% endblock %}

cadastros/templates/cadastros/form_funcionario.html
{% extends 'cadastros/form_medico.html' %}

{% load static %}


{% block crm %}

{% endblock %}

{% block campos_extras %}
    <div class="input-field col s4">
        {{ form.data_admissao }}
        <label for="{{ form.data_cadastro.id_for_label }}">Data de Admissão</label>
    </div>
    <div class="input-field col s4">
        {{ form.data_demissao }}
        <label for="{{ form.data_cadastro.id_for_label }}">Data de Demissão</label>
    </div>
{% endblock %}

{% block campo_direfente %}
    <div class="select-field col s4">
        {{ form.cargo }}
    </div>
{% endblock %}

cadastros/templates/cadastros/form_medico.html
{% extends 'paginas/index.html' %}

{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/form.css' %}">

    <style>

        #imagem-preview {
            justify-self: flex-start;
            align-self: flex-start;
            border-radius: 100%;
        }

        #imagem-preview img {
            border-radius: 100%;
        }

        .card-action {
            display: flex;
            justify-content: center;
            gap: 15px;
        }

        .btn {
            width: 140px;
        }

    </style>

    {% block estilo_form %}

    {% endblock %}
{% endblock %}


{% block content %}
<div class="card">
    <div class="card-content" style="text-align: center">
        <span class="card-title">{{titulo}}</span>
            
        <label for="{{ form.foto.id_for_label }}" id="imagem-preview">
            <img id="imagem-selecionada" src="{% static 'img/perfil-generico.jpg' %}" alt="Imagem do Paciente" style="max-width: 140px; max-height: 140px;">
            <span id="add-photo" class="icons material-symbols-outlined">Add_A_Photo</span>
        </label>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {% block campos %}
            <div class="input-field nome-field">
                {{ form.nome_completo }}
                <label for="{{ form.nome_completo.id_for_label }}">Nome completo</label>
            </div>
            
            <div class="row">
                <div class="input-field col s4">
                    <!-- {{ form.data_nascimento }} -->
                    <input type="date" id="{{ form.data_nascimento.id }}" name="{{ form.data_nascimento.name }}" value="{{ form.data_nascimento.value|date:'Y-m-d' }}">
                    <label for="{{ form.data_nascimento.id_for_label }}">Data de Nascimento</label>
                </div>

                <div class="input-field col s4">
                    {{ form.rg }}
                    <label for="{{ form.rg.id_for_label }}">RG</label>
                </div>
                
                <div class="input-field col s4">
                    {{ form.cpf }}
                    <label for="{{ form.cpf.id_for_label }}">CPF</label>
                </div>

                {% block crm %}
                    <div class="input-field col s4">
                        {{ form.crm }}
                        <label for="{{ form.crm.id_for_label }}">CRM</label>
                    </div>
                {% endblock %}

                <div class="input-field col s4">
                    {{ form.sexo }}
                </div>

                <div class="input-field col s4">
                    {{ form.endereco.rua }}
                    <label for="{{ form.rua.id_for_label }}">Rua</label>
                </div>
                
                <div class="input-field col s4">
                    {{ form.endereco.numero }}
                    <label for="{{ form.numero.id_for_label }}">Número</label>
                </div>
                
                <div class="input-field col s4">
                    {{ form.endereco.bairro }}
                    <label for="{{ form.bairro.id_for_label }}">bairro</label>
                </div>
                
                <div class="input-field col s4">
                    {{ form.endereco.cidade }}
                    <label for="{{ form.cidade.id_for_label }}">Cidade</label>
                </div>

                <div class="input-field col s4">
                    {{ form.telefone }}
                    <label for="{{ form.telefone.id_for_label }}">Telefone</label>
                </div>
                
                <div class="input-field col s4">
                    {{ form.email }}
                    <label for="{{ form.email.id_for_label }}">E-mail</label>
                </div>

                {% block campos_extras %}

                {% endblock %}

                {% block campo_direfente %}
                    <div class="select-field col s4">
                        {{ form.especialidade }}
                    </div>
                {% endblock %}
            </div>  
            
            <div class="file-field input-field">
                {{ form.foto }}
            </div>
            {% endblock%} 
            <div class="card-action">
                <button class="btn waves-effect waves-light" type="submit">Salvar</button>
                <button class="btn waves-effect waves-light" type="reset">Cancelar</button>
            </div>
        </form> 
    </div>
</div>

{% if endereco_inicial %}
    <script>
        var modoEdicao = true;
    </script>  
{% else %} 
    <script>
        var modoEdicao = false;
    </script>
{% endif %}

{% endblock %}


{% block scripts %}

    <script>
        // Inicialize os elementos do Materialize, se necessário
        M.AutoInit();
    </script>

    <script>
        // Inicialize os elementos do Materialize, se necessário
        M.AutoInit();

        // Função para mostrar a imagem selecionada

        const foto = document.getElementById('id_foto');

        foto.addEventListener('change', function() {
            const inputFoto = document.getElementById('id_foto');
            const imagemPreview = document.getElementById('imagem-preview');
            const imagemSelecionada = document.getElementById('imagem-selecionada');

            if (inputFoto.files && inputFoto.files[0]) {
                const reader = new FileReader();

                reader.onload = function (e) {
                    imagemSelecionada.src = e.target.result;
                    imagemPreview.style.display = 'block';
                };

                reader.readAsDataURL(inputFoto.files[0]);
            } else {
                imagemSelecionada.src = '#';
                imagemPreview.style.display = 'none';
            }
        })
    </script> 

    <script>
        $(document).ready(function() {

            // $('.data-mask').mask('00/00/0000');
            $('.rg-mask').mask('00.000.000-00');
            $('.cpf-mask').mask('000.000.000-00');
            $('.crm-mask').mask('CRM/AA 000000');
            var telefoneMask = function (val) {
                return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
            }, 
            telOptions = {
                onKeyPress: function(val, e, field, options) {
                    field.mask(telefoneMask.apply({}, arguments), options);
                    }
            };
            $('.telefone-mask').mask(telefoneMask, telOptions);

            if (modoEdicao) {
                $('#id_rua').val('{{ endereco_inicial.rua }}');
                $('#id_rua').focus();
                $('#id_numero').val('{{ endereco_inicial.numero }}');
                $('#id_numero').focus();
                $('#id_bairro').val('{{ endereco_inicial.bairro }}');
                $('#id_bairro').focus();
                $('#id_cidade').val('{{ endereco_inicial.cidade }}');
                $('#id_cidade').focus(); $('#id_cidade').blur();
                var foto = '{{foto.foto}}';
                if (foto) {
                    $('#imagem-selecionada').attr("src","/media/" + foto);
                } 
            }

        });

    </script>

{%endblock %}


</body>
</html>

cadastros/templates/cadastros/form_paciente.html
{% extends 'cadastros/form_medico.html' %}

{% load static %}

{% block estilo_form %}
    
{% endblock %}

{% block crm %}

{% endblock %}

{% block campo_direfente %}
    <div class="text-field col s4">
        <label id="info-med" for="{{ form.informacoes_medicas.id_for_label }}">Informações Médicas</label>
        {{ form.informacoes_medicas }}
    </div>
{% endblock %}

cadastros/templates/cadastros/modal_agenda.html
{% extends 'cadastros/agenda.html' %}

{% load static %}

{% block modal %}
    <div id="horario-form-container" class="form-container">
        <div id="horario-form" class="form-box"> 

            <h5 class="titulo-form">{{titulo}}</h5> <br>

            <form action="" method="POST" id="form-horario">
                {% csrf_token %}
                {% block form %}
                    <div class="input-field">
                        <input type="hidden" id="id_agenda" name="agenda" value="{{ agenda.id }}">
                    </div>
                    <div class="input-field" id="dias-select-box">
                        <div id="nome-medico"><span>{{agenda.medico.nome_completo}}</span> <br>({{agenda.medico.especialidade}})</div>
                        <div id="select-box">{{ form.dia_semana }}</div>
                        <p class="error" id="day-error">{{ form.dia_semana.errors.as_text|slice:"1:" }}</p>
                    </div>
                    <div class="row horarios-periodo">
                        <span class="periodo">Manhã</span>
                        <div class="input-field col s6">
                            {{ form.horario_inicial_manha }}
                            <label for="{{ form.horario_inicial_manha.id_for_label }}">Horário Inicial</label>
                        </div>
                        <div class="input-field col s6">
                            {{ form.horario_final_manha }}
                            <label for="{{ form.horario_final_manha.id_for_label }}">Horário Final</label>
                        </div>
                        <!-- {% if form.horario_inicial_manha.errors %}
                            <p class="error">{{ form.horario_inicial_manha.errors }}</p>
                        {% else %}
                            <p class="error">{{ form.horario_final_manha.errors }}</p>
                        {% endif %} -->
                        <p class="error">{{ form.horario_inicial_manha.errors.as_text|slice:"1:" }}</p>
                        <p class="error">{{ form.horario_final_manha.errors.as_text|slice:"1:" }}</p>
                    </div>
                    <div class="row horarios-periodo">
                        <span class="periodo">Tarde</span>
                        <div class="input-field col s6">
                            {{ form.horario_inicial_tarde }}
                            <label for="{{ form.horario_inicial_tarde.id_for_label }}">Horário Inicial</label>
                        </div>
                        <div class="input-field col s6">
                            {{ form.horario_final_tarde }}
                            <label for="{{ form.horario_final_tarde.id_for_label }}">Horário Final</label>
                        </div>
                        <p class="error">{{ form.horario_inicial_tarde.errors.as_text|slice:"1:" }}</p>
                        <p class="error">{{ form.horario_final_tarde.errors.as_text|slice:"1:" }}</p>
                    </div>
                    {% endblock %}
                    <div id="btn-form-box">
                        <button type="submit" class="btn btn-form">{{btn_texto}}</button>
                        <a href="{% url 'dados-agenda' agenda.pk %}" type="button" class="btn btn-form white" id="btn-cancel">Cancelar</a>
                    </div>
            </form>
        </div>
    </div>

    {% if tipo_da_view == 'CreateView' %}
        <script>
            var tipo_da_view = 'CreateView'
        </script> 
    {% elif tipo_da_view == 'UpdateView' %}
        <script>
            var tipo_da_view = 'UpdateView'
        </script> 
    {% endif %}

{% endblock %}

{% block scripts %}
    <script>
        // Inicialize os elementos do Materialize, se necessário
        M.AutoInit();
    </script>

    <script>
        $(document).ready(function () {

            console.log($('#id_agenda').val());

            $('#id_dia_semana').find("option:first").prop("disabled", true);
            $('#id_dia_semana').formSelect();

            $('#adicionar-horario').click(function () {
                $("#horario-form-container ").css('display', 'flex');
            });

            $('#btn-cancel').click(function () {
                $("#horario-form-container ").css('display', 'none');
            });
        
        });
    </script>
{% endblock %}