SisMed/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('paginas.urls')),
    path('', include('cadastros.urls')),
    path('', include('usuarios.urls')),
    path('', include('relatorios.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

paginas/urls.py
from django.urls import path
from .views import AgendamentoCreate, AgendamentoDelete, AgendamentoList, AgendamentoUpdate, AgendamentosComMedico, AtendimentoCreate, Detalhes_Agendamento, MostrarProntuario, PacientesDoDia, PacientesDoDiaMedico, ProntuarioList, RelatorioFinanceiro, IndexView, concluir_procedimento, medicos_procedimento, retornar_horarios, valor_consulta

urlpatterns = [
    #urls visualização
    path('inicio', IndexView.as_view(), name='inicio'),
    path('relatorio/financeiro', RelatorioFinanceiro.as_view(), name='relatorio-financeiro'),

    #urls cadastros
    path('agendar/consulta/procedimento', AgendamentoCreate.as_view(),  name='agendar-consulta-procedimento'),
    path('registrar/atendimento/consulta<int:pk>', AtendimentoCreate.as_view(), name='registrar-atendimento'),
    

    #urls pada edição
    path('editar/agendamento/<int:pk>', AgendamentoUpdate.as_view(), name='editar-agendamento'),
    path('concluir/procedimento', concluir_procedimento, name='concluir-procedimento'),

    #urls para deletar
    path('excluir/agendamento/<int:pk>', AgendamentoDelete.as_view(), name='excluir-agendamento'),

    #urls para listagem
    path('listar/agendamentos', AgendamentoList.as_view(), name='listar-agendamentos'),
    path('listar/agendamentos/medico', AgendamentosComMedico.as_view(), name='agendamentos-com-medico'),
    path('pacientes/dia', PacientesDoDia.as_view(), name='pacientes-do-dia'),
    path('pacientes/dia/medico', PacientesDoDiaMedico.as_view(), name='pacientes-do-dia-medico'),
    path('listar/prontuarios', ProntuarioList.as_view(), name='listar-prontuarios'),

    #urls para detalhar
    path('detalhes/agendamento/<int:pk>', Detalhes_Agendamento.as_view(), name='detalhes_agendamento'),
    path('dados/prontuario/<int:pk>', MostrarProntuario.as_view(), name='dados_prontuario'),

    # Urls para requisições json
    path('medico_responsavel/<int:procedimento_id>/', medicos_procedimento, name='medicos_procedimento'),
    path('retornar-horarios', retornar_horarios, name='retornar-horarios'),
    path('valor-consulta', valor_consulta, name='valor-consulta'),
]

cadastros/models.py
from django.db import models
from datetime import date, datetime
from django.contrib.auth.models import User

sexo_opcoes = (('M', 'Masculino'), ('F', 'Feminino'))
boolean_opcoes = ((True, 'Sim'), (False, 'Não'))
tipo_agendamento_opcoes = (('Consulta', 'Consulta'), ('Procedimento', 'Procedimento'))
tipo_pagamento_opcoes = (('Plano', 'Plano'), ('Particular', 'Particular'))
dias_semana_opcoes = ((0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'))

# Create your models here.
class Endereco(models.Model):
    rua = models.CharField(max_length=50)
    numero = models.IntegerField(null=True, blank=True, verbose_name='Número')
    bairro = models.CharField(max_length=50)
    cidade = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.rua} {self.numero} {self.bairro} {self.cidade}'


class Cargo(models.Model):
    nome_cargo = models.CharField(max_length=50, unique=True, verbose_name='Nome do cargo')
    salario = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Salário')

    def __str__(self):
        return f'{self.nome_cargo} {self.salario}'


class Funcionario(models.Model):
    nome_completo = models.CharField(max_length=100, verbose_name='Nome Completo')
    data_nascimento = models.DateField(verbose_name='Data de Nascimento')
    rg = models.CharField(max_length=13, verbose_name='RG', unique=True)
    cpf = models.CharField(max_length=14, verbose_name='CPF', unique=True)
    sexo = models.CharField(max_length=1, choices=sexo_opcoes, null=True) 
    endereco = models.OneToOneField(Endereco, null=True, on_delete=models.PROTECT)
    telefone = models.CharField(max_length=15, unique=True) 
    email = models.CharField(max_length=50, unique=True) 
    data_admissao = models.DateField(null=True, verbose_name='Data de Admissão')
    data_demissao = models.DateField(null=True, blank=True, verbose_name='Data de Demissão')
    cargo = models.ForeignKey(Cargo, on_delete=models.PROTECT) 
    foto =  models.ImageField(upload_to='fotos_funcionarios', blank=True, null=True)
    usuario = models.OneToOneField(User, null=True, blank=True, on_delete=models.DO_NOTHING)

    def get_idade(self):
        hoje = datetime.now().date()
        idade = hoje.year - self.data_nascimento.year - ((hoje.month, hoje.day) < (self.data_nascimento.month, self.data_nascimento.day))
        return idade

    def __str__(self):
        return f'{self.nome_completo}'

    """def __str__(self):
        return f'{self.nome_completo} {self.data_nascimento} {self.rg} {self.cpf} {self.endereco} {self.telefone} {self.email} {self.data_admissao} {self.data_demissao} {self.cargo}'"""


class Especialidade(models.Model):
    especialidade = models.CharField(max_length=30, unique=True)
    valor_consulta = models.DecimalField(max_digits=8, decimal_places=2, null=True)

    def __str__(self):
        return f'{self.especialidade}'


class Medico(models.Model):
    nome_completo = models.CharField(max_length=100, verbose_name='Nome Completo')
    data_nascimento = models.DateField(verbose_name='Data de Nascimento')
    rg = models.CharField(max_length=13, verbose_name='RG', unique=True)
    cpf = models.CharField(max_length=14, verbose_name='CPF', unique=True)
    crm = models.CharField(null=True, max_length=14, verbose_name='CRM', unique=True)
    sexo = models.CharField(max_length=1, choices=sexo_opcoes, null=True) 
    endereco = models.OneToOneField(Endereco, null=True, on_delete=models.PROTECT)
    telefone = models.CharField(max_length=15, unique=True) 
    email = models.CharField(max_length=50, unique=True) 
    data_cadastro = models.DateField(verbose_name='Data de Cadastro') 
    especialidade = models.ForeignKey(Especialidade, on_delete=models.PROTECT)
    foto =  models.ImageField(upload_to='fotos_medicos', blank=True, null=True)
    usuario = models.OneToOneField(User, null=True, on_delete=models.DO_NOTHING)

    def save(self, *args, **kwargs):
        if not self.data_cadastro:
            self.data_cadastro = date.today()
        super().save(*args, **kwargs)

    def get_idade(self):
        hoje = datetime.now().date()
        idade = hoje.year - self.data_nascimento.year - ((hoje.month, hoje.day) < (self.data_nascimento.month, self.data_nascimento.day))
        return idade
    
    def __str__(self):
        return f'{self.nome_completo} - {self.especialidade}'

    """def __str__(self):
        return f'{self.nome_completo} {self.data_nascimento} {self.rg} {self.cpf} {self.crm} {self.endereco} {self.telefone} {self.email} {self.data_cadastro} {self.especialidade}'"""


class Paciente(models.Model):
    nome_completo = models.CharField(max_length=100, verbose_name='Nome Completo')
    data_nascimento = models.DateField(verbose_name='Data de Nascimento')
    rg = models.CharField(max_length=13, verbose_name='RG', unique=True)
    cpf = models.CharField(max_length=14, verbose_name='CPF', unique=True)
    sexo = models.CharField(max_length=1, choices=sexo_opcoes, null=True) 
    endereco = models.OneToOneField(Endereco, null=True, on_delete=models.PROTECT)
    telefone = models.CharField(max_length=15) 
    email = models.CharField(max_length=50) 
    data_cadastro = models.DateField(verbose_name='Data de Cadastro') 
    informacoes_medicas = models.TextField(verbose_name='Informações Médicas')
    foto =  models.ImageField(upload_to='fotos_pacientes', blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.data_cadastro:
            self.data_cadastro = date.today()
        super().save(*args, **kwargs)

    def get_idade(self):
        hoje = datetime.now().date()
        idade = hoje.year - self.data_nascimento.year - ((hoje.month, hoje.day) < (self.data_nascimento.month, self.data_nascimento.day))
        return idade

    def __str__(self):
        return f'{self.nome_completo}'

    """def __str__(self):
        return f'{self.nome_completo} {self.data_nascimento} {self.rg} {self.cpf} {self.endereco} {self.telefone} {self.email} {self.data_cadastro} {self.informacoes_medicas}'"""
    

class HorarioAtendimento(models.Model):
    horario_atendimento = models.TimeField(unique=True)

    def __str__(self):
        return f'{self.horario_atendimento}'


class AgendaMedico(models.Model):
    medico = models.OneToOneField(Medico, on_delete=models.CASCADE)
    
    def __str__(self):
        return f'{self.medico}'


class HorarioMedico(models.Model):
    agenda = models.ForeignKey(AgendaMedico, null=True, on_delete=models.CASCADE)
    dia_semana = models.IntegerField(choices=dias_semana_opcoes)
    horario_inicial_manha = models.TimeField(null=True, blank=True)
    horario_final_manha = models.TimeField(null=True, blank=True)
    horario_inicial_tarde = models.TimeField(null=True, blank=True)
    horario_final_tarde = models.TimeField(null=True, blank=True)


class Prontuario(models.Model):
    data_criacao = models.DateField()
    paciente = models.OneToOneField(Paciente, on_delete=models.PROTECT)

    def save(self, *args, **kwargs):
        if not self.data_criacao:
            self.data_criacao = date.today()
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.data_criacao} {self.paciente}'


class Procedimento(models.Model): 
    nome_procedimento = models.CharField(max_length=50, null=True)
    especialidade_responsavel = models.ForeignKey(Especialidade, on_delete=models.PROTECT, null=True, blank=True)
    descricao = models.TextField(null=True, verbose_name='Descricão')
    valor_procedimento = models.DecimalField(max_digits=8, decimal_places=2, null=True)
    observacao = models.TextField(null=True, blank=True, verbose_name='Observações Gerais Sobre o Procedimento')

    def __str__(self):
        return f'{self.nome_procedimento}' 
    

class Agendamento(models.Model):
    tipo_agendamento = models.CharField(max_length=12, default='Consulta', choices=tipo_agendamento_opcoes, verbose_name='Tipo de agendamento')
    procedimento = models.CharField(max_length=50, null=True, blank=True)
    data = models.DateField(null=True)
    horario = models.TimeField(null=True, verbose_name='Horário')
    paciente = models.ForeignKey(Paciente, on_delete=models.PROTECT)
    medico = models.ForeignKey(Medico, on_delete=models.PROTECT)
    tipo_pagamento = models.CharField(max_length=10, default='Particular', choices=tipo_pagamento_opcoes, verbose_name='Tipo de pagamento')
    retorno = models.BooleanField(default=False, choices=boolean_opcoes)
    valor = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Valor')
    concluido = models.BooleanField(default=False, null=True)

    def __str__(self):
        return f'{self.tipo} {self.data} {self.horario} {self.paciente} {self.medico} {self.concluido}' 


class Atendimento(models.Model):
    data = models.DateField(null=True)
    consulta = models.OneToOneField(Agendamento, on_delete=models.PROTECT)
    anamnese_paciente = models.TextField(verbose_name="Anamnese do paciente")
    diagnostico = models.TextField(verbose_name="Diagnóstico")
    receituario = models.TextField(verbose_name="Receituário/Recomendações") 

    def save(self, *args, **kwargs):
        if not self.data:
            self.data = date.today()
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.nota_medico} {self.paciente} {self.medico}'

paginas/models.py
from django.db import models

# Create your models here.

paginas/forms.py
from datetime import datetime
from django import forms
from cadastros.models import Atendimento, Medico, Agendamento, Paciente, Procedimento, tipo_agendamento_opcoes, boolean_opcoes, tipo_pagamento_opcoes

class AgendamentoForm(forms.ModelForm):
    tipo_agendamento = forms.ChoiceField(choices=tipo_agendamento_opcoes, widget=forms.RadioSelect(attrs={'class': 'with-gap'}), initial='Consulta')
    procedimento = forms.ModelChoiceField(queryset=Procedimento.objects.all(), empty_label="Selecionar Procedimento", widget=forms.Select(attrs={'class': 'select'}), required=False)
    paciente = forms.ModelChoiceField(queryset=Paciente.objects.all(), empty_label="Selecionar Paciente", widget=forms.Select(attrs={'class': 'select'}))
    medico = forms.ModelChoiceField(queryset=Medico.objects.all(), empty_label="Selecionar Médico/Especialidade", widget=forms.Select(attrs={'class': 'select'}))
    data = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    horario = forms.CharField(widget=forms.Select(attrs={'class': 'select'}))
    tipo_pagamento = forms.ChoiceField(choices=[('', 'Plano/Particular?')] + list(tipo_pagamento_opcoes), widget=forms.Select(attrs={'class': 'select'}))
    retorno = forms.ChoiceField(choices=[('', 'Retorno?')] + list(boolean_opcoes), widget=forms.Select(attrs={'class': 'select'}), required=False)
    valor = forms.DecimalField(label='Valor da Consulta')

    class Meta:
        model = Agendamento
        fields = ['tipo_agendamento','procedimento','data', 'horario', 'paciente', 'medico', 'tipo_pagamento', 'retorno', 'valor']

    def clean_horario(self):
        horario_str = self.cleaned_data['horario']
        try:
            horario_str += ':00'
            horario = datetime.strptime(horario_str, '%H:%M:%S').time()
            return horario
        except ValueError:
            raise forms.ValidationError("Formato de horário inválido. Use HH:MM")
    

class AtendimentoForm(forms.ModelForm):
    class Meta:
        model = Atendimento
        fields = ['consulta', 'anamnese_paciente', 'diagnostico', 'receituario']

paginas/templates/paginas/form_agendamento.html
{% extends 'paginas/index.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    <style>

        #agendamento-form {
            padding-bottom: 10px;
        }

        .row {
            border: 1px solid #2bb9ab;
            margin-block: 0;
            margin-inline: 10px;
        }

        .tipo_agendamento {
            border-bottom: 0;
            border-top-left-radius: 2px; 
            border-top-right-radius: 2px; 
            padding: 0;
        }

        .tipo_agendamento col {
            padding: 0;
        }

        .campos-agendamento {
            border-bottom-left-radius: 2px; 
            border-bottom-right-radius: 2px; 
        }

        #input-radio-box {
            display: flex;
            gap: 15px;
        }

        #procedimento_select {
            display: none;
        }

        #btn-box {
            display: flex;
            justify-content: flex-end;
        }

        .btn {
            width: 125px;
            align-self: flex-end;
            justify-self: flex-end;
            margin-top: -5px;
            margin-bottom: 12px;
            /* margin-right: 10px; */
            /* margin-bottom: -20px; */
        }

        #campo-data-box {
            position: relative;
        }

        #erro-data {
            display: none;
            width: 250px;
            font-size: 14px;
            left: -5px;
            bottom: -15px;
        }

    </style>
{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-content" style="text-align: center">
            <span class="card-title">Agendamento de Consulta/Procedimento</span> <br>
            
            <form action="" method="POST" id="agendamento-form">
                {% csrf_token %}
                {{ form.errors }}
                <div class="row tipo_agendamento">
                    <div class="input-field col s6" id="input-radio-box">
                        {% for radio in form.tipo_agendamento %}
                            <p>
                                <label class="radio-label">
                                    {{ radio.tag }}
                                    <span>{{ radio.choice_label }}</span>
                                </label>
                            </p>
                        {% endfor %}
                    </div>
                    <div class="input-field col s6" id="procedimento_select">
                        {{ form.procedimento }}
                    </div>
                    <div class="input-field col s6"  id="retorno_select">
                        {{ form.retorno }}
                    </div>
                </div>
                <div class="row campos-agendamento">
                    <div class="input-field col s6">
                        {{ form.paciente }}
                    </div>
                    <div class="input-field col s6">
                        {{ form.medico }}
                    </div>
                    <div class="input-field col s3" id="campo-data-box">
                        <input type="date" id="id_data" name="{{ form.data.name }}" value="{{ form.data.value|date:'Y-m-d' }}">
                        <label for="{{ form.data.id_for_label }}">Data</label>
                        <p class="error" id="erro-data">Data inválida! Esta data já passou.</p>
                    </div>
                    <div class="input-field col s3">
                        {{ form.horario }}
                    </div>
                    <div class="input-field col s4">
                        {{ form.tipo_pagamento }}
                    </div>
                    <div class="input-field col s2">
                        {{ form.valor }}
                        <label for="{{ form.valor.id_for_label }}">Valor</label>
                    </div>
                    <div class="input-field col s12" id="btn-box">
                        <button type="submit" class="btn btn-form">Agendar</button>
                    </div>
                </div>
            </form>
        </div> 
    </div> 

    {% if type_view == 'CreateView' %}
        <script>
            var type_view = 'CreateView';
        </script>  
    {% elif type_view == 'UpdateView' %} 
        <script>
            var type_view = 'UpdateView';
            var horario_inicial = '{{ horario }}';
            var procedimento_id = '{{ procedimento_id }}';
            var data_recebida = '{{ data }}';
        </script>
    {% endif %}

{% endblock %}

{% block scripts %}

<script>M.AutoInit();</script>
<script src="{% static 'js/agendamento.js' %}"></script>

{% endblock %}

paginas/templates/paginas/index.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% block titulo %}
        <title>SisMed</title>
    {% endblock %}

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    
    <link rel="stylesheet" href="{% static 'css/estilo.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_dash.css' %}">

    {% block styles %}

    {% endblock %}

</head>
<body>

{% block head %}
<header>
    <a href="#" class="brand-logo">
        <img id="logo" src="{% static 'img/SisMed-logo.png' %}" alt="SisMed logo" class="responsive-img" style="max-height: 60px;">
    </a>

  <nav class="navbar-nav">
    
    <div class="nav-wrapper" >
      
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                {% if request.user.is_authenticated %}
                    <li class="dropdown-trigger black-text" data-target="dropdown1">
                        <!-- <i class="fa-solid fa-border-all"></i> -->
                        <span class="icons material-symbols-outlined" id="view-cozy">View_Cozy</span>
                        Menu
                    </li>
                    {% if is_admin or request.user.is_superuser %}
                    <li class="dropdown-trigger black-text" data-target="dropdown2">
                            <span class="icons material-symbols-outlined" id="add-box">add_box</span>
                            Cadastrar
                    </li>
                    {% endif %}
                    <li id="drop-user" class="dropdown-trigger black-text" data-target="dropdown3"> {{ request.user }}
                        <span class="material-symbols-outlined">arrow_drop_down</span>
                    </li>
                {% else %}
                    <li><a class="black-text" id="login-option" href="{% url 'login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <ul id="dropdown1" class="dropdown-content">
        {% if is_medico %}
            <li><a href="{% url 'dados-agenda' request.user.medico.agendamedico.pk %}">Minha Agenda</a></li>
            <li><a href="{% url 'listar-pacientes-medico' %}">Meus Pacientes</a></li>
            <li><a href="{% url 'agendamentos-com-medico' %}">Agendamentos</a></li>
            <li><a href="{% url 'pacientes-do-dia-medico' %}">Pacientes do Dia</a></li>
        {% else %}
            <li><a href="{% url 'listar-cargos' %}">Listar Cargos</a></li>
            <li><a href="{% url 'listar-especialidades' %}">Listar Especialidades</a></li>
            <li><a href="{% url 'listar-funcionarios' %}">Listar Funcionários</a></li>
            <li><a href="{% url 'listar-medicos' %}">Listar Médicos</a></li>
            <li><a href="{% url 'listar-pacientes' %}">Listar Pacientes</a></li>
            <li><a href="{% url 'listar-procedimentos' %}">Listar Procedimentos</a></li>
            <li><a href="{% url 'listar-agendamentos' %}">Agendamentos</a></li>
            <li><a href="{% url 'pacientes-do-dia' %}">Pacientes do Dia</a></li>
            <li><a href="{% url 'relatorio-financeiro' %}">Relatório Financeiro</a></li>
        {% endif %}
    </ul>
    
    <ul id="dropdown2" class="dropdown-content">
        <li><a href="{% url 'cadastrar-cargo' %}">Cargo</a></li>
        <li><a href="{% url 'cadastrar-especialidade' %}">Especialidade</a></li>
        <li><a href="{% url 'cadastrar-funcionario' %}">Funcionário</a></li>
        <li><a href="{% url 'cadastrar-medico' %}">Médico</a></li>
        <li><a href="{% url 'cadastrar-paciente' %}">Paciente</a></li>
        <li><a href="{% url 'cadastrar-usuario' %}">Usuario</a></li>
        <li><a href="{% url 'cadastrar-procedimento' %}">Procedimento</a></li>
    </ul>

    <ul id="dropdown3" class="dropdown-content">
        <li><a href="{% url 'inicio' %}">Início</a></li>
        {% if request.user.is_superuser %}
            <li><a href="/admin">Painel Administrativo</a></li> 
        {% endif %}
        <li><a href="{% url 'logout' %}">Sair</a></li>
    </ul>


</div>
</header>
{% endblock %}

{% block main %}
<main>
    <div class="container" id="main-container">
        {% block content %}
            <div class="row">
                <div class="col s12 flex align-center" id="bem-vindo">
                    <h4>Bem-vindo, <span>{{request.user}}</span>!</h4> &nbsp; <a class="btn btn-agendar" href="{% url 'agendar-consulta-procedimento' %}">Agendar Atendimento</a>
                </div>
            </div>
        
            <div class="row">
                {% if is_medico %}
                    <a href="{% url 'dados-agenda' request.user.medico.agendamedico.pk %}">
                        <div class="col s12 m6 l4">
                            <div class="card custom-card">
                                <div class="card-content" id="card-agenda">
                                    <i class="fa-regular fa-calendar-check fa-7x"></i>
                                    <span class="card-title">Minha Agenda</span>
                                </div>
                            </div>
                        </div>
                    </a>
                {% else %}
                    <a href="{% url 'listar-medicos' %}">
                        <div class="col s12 m6 l4">
                            <div class="card custom-card">
                                <div class="card-content">
                                    <i class="fas fa-user-md fa-3x"></i>
                                    <span class="card-title">Médicos <br>Cadastrados</span>
                                    <p class="card-data">{{qtd_medicos}}</p>
                                </div>
                            </div>
                        </div>
                    </a>
                {% endif %}
        
                <a href="{% if is_medico %} {% url 'listar-pacientes-medico' %} {% else %} {% url 'listar-pacientes' %} {% endif %}"> 
                    <div class="col s12 m6 l4">
                        <div class="card custom-card">
                            <div class="card-content">
                                <i class="fas fa-user fa-3x"></i>
                                <span class="card-title">{{titulo_card_pacientes}}</span>
                                <p class="card-data">{{qtd_pacientes}}</p>
                            </div>
                        </div>
                    </div>
                </a>
                
                <a href="{% if is_medico %} {% url 'pacientes-do-dia-medico' %} {% else %} {% url 'pacientes-do-dia' %} {% endif %}">
                    <div class="col s12 m6 l4">
                        <div class="card custom-card">
                            <div class="card-content">
                                <i class="fas fa-user-injured fa-3x"></i>
                                <span class="card-title">Pacientes do Dia</span>
                                <p style="font-size: 20px;">Data: {{data_atual|date:'d/m/Y'}}</p>
                                <p class="card-data">{{qtd_consultas}}</p>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col s12 m6 l6">
                <div class="card dynamic-card">
                    <div class="card-content">
                        <span class="card-title">Especialidades Mais Requisitadas</span>
                        <table class="specialties-table">
                            <thead>
                                <tr>
                                    <th>Especialidade</th>
                                    <th>Número de médicos</th>
                                    <th>Médicos disponíveis</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for especialidade in especialidades_mais_requisitadas %}
                                <tr>
                                    <td>{{especialidade.especialidade}}</td>
                                    <td>{{especialidade.medico_set.all|length}}</td>
                                    <td>{{especialidade.medico_set.all|length}}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        {% endblock %}
    </div>
</main>
{% endblock %}

{% block footer %}
<footer>
    <div class="col-12" id="copyright">
        <p>&copy; 2023 Copyright SisMed</p>
    </div>
</footer>
{% endblock %}

<!-- Scripts -->
<script src="{% static 'js/jquery-3.7.0.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/5.0.6/jquery.inputmask.min.js"></script>
<script src="{% static 'js/jquery.mask.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<script src="{% static 'js/fontawesome.js' %}"></script>
<script>
    // Inicialização do menu dropdown
    $(document).ready(function(){
        $('.dropdown-trigger').dropdown();
    });
</script>

{% block scripts %}

{% endblock %}
</body>
</html>